# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

steps:
- powershell: ./PowerShell/InstallPSWVD.ps1
  displayName: 'Install WVD Module'

- task: CopyFiles@2
  displayName: 'Copy powershell content'
  inputs: 
    SourceFolder: '$(Build.SourcesDirectory)/PowerShell'
    contents: '**\*' 
    targetFolder: $(Build.ArtifactStagingDirectory)/PowerShell
    cleanTargetFolder: true

- task: CopyFiles@2
  displayName: 'Copy WVD Templaates content'
  inputs: 
    SourceFolder: '$(Build.SourcesDirectory)/WVD Templates'
    contents: '**\*' 
    targetFolder: $(Build.ArtifactStagingDirectory)/WVD Templates
    cleanTargetFolder: true